immune = c(
  "COVID19_HGI_A2",
  "PASS_Lupus",
  "PASS_Rheumatoid_Arthritis",
  "PASS_Multiple_sclerosis",
  "PASS_Primary_biliary_cirrhosis",
  # "PASS_CD_deLange2017",
  "PASS_Crohns_Disease",
  # "PASS_IBD_deLange2017",
  # "PASS_IBD",
  "PASS_Celiac",
  # "PASS_UC_deLange2017",
  "PASS_Ulcerative_Colitis",
  "PASS_AdultOnsetAsthma_Ferreira2019",
  "PASS_ChildOnsetAsthma_Ferreira2019",
  # "UKB_460K.disease_AID_ALL",
  # "UKB_460K.disease_AID_SURE",
  "UKB_460K.disease_ALLERGY_ECZEMA_DIAGNOSED",
  # "UKB_460K.disease_ASTHMA_DIAGNOSED",
  "UKB_460K.disease_HYPOTHYROIDISM_SELF_REP",
  "UKB_460K.disease_PSORIASIS",
  "Lopez_SSc",
  "Taylor_SjS",
  "Ishigaki_RA",
  "Patsopoulos_MS",
  "UKB_460K.disease_AOSD",
  "UKB_460K.disease_SpA_SELF_REP",
  "UKB_460K.disease_AS_SELF_REP")
CNS = c(
  "PASS_ADHD_Demontis2018",
  # "PASS_AlzheimersMaternal_Marioni2018",
  # "PASS_AlzheimersPaternal_Marioni2018",
  # "PASS_AlzheimersProxy_Marioni2018",
  "PASS_Alzheimers_Jansen2019",
  "PASS_AnorexiaNervosa_Duncan_2017",
  "PASS_Autism_Grove2019",
  # "PASS_BDSCZ_Ruderfer2018",
  # "PASS_BIP_Stahl2019",
  "PASS_Bipolar_Disorder",
  "PASS_Depression_Nagel2018",
  # "PASS_DS",
  # "PASS_DepressedAffect_Nagel2018",
  "PASS_Epilepsy_Anney_2014",
  "PASS_Insomnia_Jansen2019",
  "PASS_Intelligence_SavageJansen2018",
  "PASS_MDD_Howard2019",
  # "PASS_MDD_Wray2018",
  # "PASS_Neuroticism",
  # "PASS_Neuroticism_Nagel2018",
  "PASS_Parkinsons_23andMe_Corces2020",
  "PASS_Schizophrenia",
  # "PASS_Schizophrenia_Pardinas2018",
  # "PASS_Schizophrenia_Ruderfer2018",
  # "PASS_SCZvsBD_Ruderfer2018",
  # "UKB_460K.mental_NEUROTICISM",
  "Rheenen_ALS")
cancer = c(
  "PASS_BreastCancer",
  "PASS_OvarianCancer",
  "PASS_ProstateCancer",
  "UKB_460K.cancer_ALL",
  "UKB_460K.cancer_PROSTATE",
  "UKB_460K.cancer_BREAST",
  "UKB_460K.cancer_MELANOMA")
metabo = c(
  "PASS_BMI1",
  "PASS_FastingGlucose_Manning",
  "PASS_HDL",
  "PASS_HbA1C",
  "PASS_LDL",
  "PASS_Triglycerides",
  "PASS_Type_2_Diabetes",
  "UKB_460K.biochemistry_ApolipoproteinA",
  "UKB_460K.biochemistry_ApolipoproteinB",
  "UKB_460K.biochemistry_Cholesterol",
  "UKB_460K.biochemistry_Glucose",
  "UKB_460K.biochemistry_HDLcholesterol",
  "UKB_460K.biochemistry_HbA1c",
  "UKB_460K.biochemistry_LDLdirect",
  "UKB_460K.biochemistry_LipoproteinA",
  "UKB_460K.biochemistry_Triglycerides",
  "UKB_460K.body_BMIz",
  "UKB_460K.disease_DIABETES_ANY_DIAGNOSED",
  "UKB_460K.disease_HI_CHOL_SELF_REP",
  "UKB_460K.disease_T2D"
)
